import type { Metadata } from "next";
import { Inter } from "next/font/google";
// Components
import ProfileBtn from "@/components/ProfileBtn";
import UserBalance from "@/components/UserBalance";
// Fonts
import { lexend } from "@/fonts";
// Styles
import "./globals.css";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lexend.className}>
      <body>
        <header className={styles.nav_header}>
          <nav className={styles.nav_wrapper}>
            <h1>StakeSim</h1>
            <UserBalance />
            <ProfileBtn />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
