import type { Metadata } from "next";
import { Inter } from "next/font/google";
// Components
import ProfileBtn from "@/components/ProfileBtn";
import styles from "./layout.module.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.nav_header}>
          <nav className={styles.nav_wrapper}>
            <h1>StakeSim</h1>
            <ProfileBtn />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
